CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    salt VARCHAR(100),
    enabled BOOLEAN DEFAULT true,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL
); 